version: '3.9'
services:
  server:
    build:
      context: ../images
      dockerfile: ./${!IMAGE}
    container_name: ${!DOMAIN}-app
    restart: always
    ports:
      - '${!PUBLIC}${!PORT}:80'
    volumes:
      - /var/containers/domains/${!DOMAIN}:/srv/www
